name: Discord Engagement Stats Collection (Deployed API)

on:
  workflow_dispatch:
    inputs:
      backfill:
        description: "Run backfill for historical data"
        required: false
        default: false
        type: boolean
      year:
        description: "Year to backfill from"
        required: false
        default: "2025"
        type: string

jobs:
  discord-engagement-stats:
    name: Discord Engagement Statistics (Deployed API)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Discord engagement stats collection via deployed API
        run: node scripts/github-actions/discord-stats-api.js
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://your-app.vercel.app' }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          OUTPUT_FILE: ${{ github.workspace }}/discord-stats/stats.json
          BACKFILL: ${{ github.event.inputs.backfill || 'false' }}
          BACKFILL_YEAR: ${{ github.event.inputs.year || '2025' }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add discord-stats/
          git diff --quiet && git diff --staged --quiet || git commit -m "📊 Update Discord engagement stats via API - $(date +%Y-%m-%d)"
          git push 